# My confg
theme = "kanagawa"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
C = ["ensure_selections_forward", "extend_to_line_end", "change_selection"]
A-left = ["goto_previous_buffer"]
A-right = ["goto_next_buffer"]
A-w = ":buffer-close"
"C-d" = ["half_page_down", "goto_window_center"]
"C-u" = ["half_page_up", "goto_window_center"]

[keys.normal."]"]
"]" = "goto_next_paragraph"

[keys.normal."["]
"[" = "goto_prev_paragraph"

[keys.select."]"]
"]" = "goto_next_paragraph"

[keys.select."["]
"[" = "goto_prev_paragraph"